Repository scikit-hep/pyhf, pull requests merged in 2018-09, with the labels that each got.

#233 add qualify-names option for pyhf cls
  pyhf/commandline.py
Labels: enhancement

#234 Allow for configurable measurement to be specified from command line
  pyhf/commandline.py
  tests/test_scripts.py
Labels: enhancement

#236 Feature: add op_code to modifiers
  pyhf/modifiers/__init__.py
  tests/test_modifiers.py
Labels: enhancement

#235 Install NumPy through SciPy's dependency on it
  .travis.yml
  CONTRIBUTING.md
  docs/development.rst
  setup.py
Labels: enhancement

#237 Install with --ignore-installed to ensure proper NumPy
  .travis.yml
  CONTRIBUTING.md
  docs/development.rst
Labels: enhancement

#232 Feature: maintain union of specification items as part of the model
  pyhf/pdf.py
Labels: enhancement

#241 Feature: make schema stricter (require minItems for some arrays)
  pyhf/data/spec.json
  pyhf/exceptions/__init__.py
  pyhf/pdf.py
  tests/test_schema.py
Labels: bug, enhancement

#242 Include readme in top-level docs
  README.md
  docs/Makefile
  docs/_static/img/hfh_1bin_55_50_7.png
  docs/_static/img/hfh_2_bin_100.0_145.0_100.0_150.0_15.0_20.0_30.0_45.0.png
  docs/_static/img/manual_1bin_55_50_7.png
  docs/_static/img/manual_2_bin_100.0_145.0_100.0_150.0_15.0_20.0_30.0_45.0.png
  docs/conf.py
  docs/index.rst
  setup.py
Labels: docs

#245 Remove Docker Hub build status badge
  README.md
Labels: docs

#262 Fix concatenate and add missing functionality to backends:
  pyhf/tensor/mxnet_backend.py
  pyhf/tensor/numpy_backend.py
  pyhf/tensor/pytorch_backend.py
  pyhf/tensor/tensorflow_backend.py
  tests/test_tensor.py
Labels: enhancement

#251 Feature: tensorize the interpolation codes (more general)
  docs/examples/notebooks/learn/TensorizingInterpolations.ipynb
  pyhf/interpolate.py
  pyhf/modifiers/histosys.py
  pyhf/modifiers/normsys.py
  tests/test_interpolate.py
  tests/test_tensor.py
Labels: enhancement

#276 Feature: (automatically) set backends through a fixture
  pyhf/readxml.py
  tests/conftest.py
  tests/test_init.py
  tests/test_interpolate.py
  tests/test_optim.py
  tests/test_pdf.py
  tests/test_tensor.py
Labels: enhancement

#277 Use scipy.special.xlogy in poisson computation for numpy backend
  pyhf/tensor/numpy_backend.py
Labels: enhancement

#261 Add complete install option
  .travis.yml
  docs/development.rst
  setup.py
Labels: enhancement
