Repository scikit-hep/pyhf, pull requests merged in 2018-10, with the labels that each got.

#287 Updates the backend to get ready for full refactor
  .travis.yml
  pyhf/readxml.py
  pyhf/tensor/mxnet_backend.py
  pyhf/tensor/numpy_backend.py
  pyhf/tensor/pytorch_backend.py
  pyhf/tensor/tensorflow_backend.py
  pytest.ini
  setup.py
  tests/test_interpolate.py
  tests/test_tensor.py
Labels: enhancement

#294 Add boolean_mask back to backend
  pyhf/tensor/mxnet_backend.py
  pyhf/tensor/numpy_backend.py
  pyhf/tensor/pytorch_backend.py
  pyhf/tensor/tensorflow_backend.py
  tests/test_tensor.py
Labels: bug, enhancement

#291 Update optimizers to allow for custom iterations for constrained fits
  pyhf/optimize/opt_pytorch.py
  pyhf/optimize/opt_tflow.py
Labels: enhancement

#296 Use TensorFlow Probability for distributions
  .travis.yml
  pyhf/tensor/tensorflow_backend.py
  setup.py
Labels: enhancement

#299 Have Selenium properly wait for page load
  .travis.yml
  binder/trigger_binder.py
Labels: docs

#304 Add version info through __version__
  .bumpversion.cfg
  .github/ISSUE_TEMPLATE/bug-report.md
  pyhf/__init__.py
  pyhf/version.py
Labels: enhancement

#300 begin separation of constraints and modifiers
  pyhf/modifiers/__init__.py
  pyhf/modifiers/histosys.py
  pyhf/modifiers/normfactor.py
  pyhf/modifiers/normsys.py
  pyhf/modifiers/shapefactor.py
  pyhf/modifiers/shapesys.py
  pyhf/modifiers/staterror.py
  pyhf/paramsets.py
  pyhf/pdf.py
  tests/test_constraints.py
  tests/test_modifiers.py
Labels: enhancement

#309 continue separating mods / parsets
  pyhf/constraints.py
  pyhf/modifiers/histosys.py
  pyhf/modifiers/normsys.py
  pyhf/modifiers/shapesys.py
  pyhf/modifiers/staterror.py
  tests/test_constraints.py
Labels: enhancement

#310 remove unneeded methods
  pyhf/modifiers/staterror.py
  pyhf/paramsets.py
  tests/test_constraints.py
  tests/test_modifiers.py
Labels: enhancement

#305 Add additional pdf information to aid with refactoring
  .ackrc
  pyhf/pdf.py
  tests/test_pdf.py
Labels: enhancement

#311 Add a way to subscribe/trigger events globally
  pyhf/events.py
  tests/test_events.py
Labels: enhancement, research

#319 Have bumpversion update version on website
  .bumpversion.cfg
  docs/conf.py
Labels: docs

#318 Add citations and use cases to website
  docs/bib/use_citations.bib
  docs/citations.rst
  docs/index.rst
Labels: docs

#326 Remove notebooks untested in the CI from website examples
  docs/examples.rst
Labels: docs

#328 Improve installation instruction clarity
  docs/api.rst
  docs/citations.rst
  docs/installation.rst
  docs/talks.rst
Labels: docs

#329 Insert the POI parameter correctly using POI index in opt_tflow
  pyhf/optimize/opt_tflow.py
  tests/test_backend_consistency.py
Labels: bug

#333 fix up indexing of summed_mask in shapesys, staterror
  pyhf/modifiers/shapesys.py
  pyhf/modifiers/staterror.py
Labels: enhancement

#338 Add README to PyPI
  setup.py
Labels: docs

#339 Add wheel deployment to PyPI from Travis CI
  .travis.yml
  setup.cfg
Labels: enhancement

#340 Use version dependent open to get README
  setup.py
Labels: bug

#337 Add new interpolator codes 2 (two) and 4 (four)
  docs/api.rst
  pyhf/interpolate.py
  pyhf/interpolators/__init__.py
  pyhf/interpolators/code0.py
  pyhf/interpolators/code1.py
  pyhf/interpolators/code2.py
  pyhf/interpolators/code4.py
  pyhf/modifiers/histosys.py
  pyhf/modifiers/normsys.py
  tests/conftest.py
  tests/test_interpolate.py
Labels: enhancement

#265 Add a FAQ to the website
  docs/conf.py
  docs/faq.rst
  docs/index.rst
  setup.py
Labels: docs

#345 Fix table in README to be rendered properly in docs
  README.md
Labels: docs

#347 Make GitHub install instructions easier
  docs/development.rst
  docs/installation.rst
Labels: docs

#350 Add more talks on pyhf, add an initial abstract.
  docs/bib/talks.bib
  docs/talks.rst
Labels: docs

#353 Use mathmode outside of bold environment
  docs/examples/notebooks/hello-world.ipynb
Labels: docs
