Repository scikit-hep/pyhf, pull requests merged in 2018-05, with the labels that each got.

#149 Add tensor aware test stats
  .travis.yml
  examples/notebooks/ShapeFactor.ipynb
  examples/notebooks/multiBinPois.ipynb
  examples/notebooks/multichannel-coupled-histo.ipynb
  pyhf/__init__.py
  pyhf/optimize/opt_pytorch.py
  pyhf/tensor/__init__.py
  pyhf/tensor/mxnet_backend.py
  pyhf/tensor/numpy_backend.py
  pyhf/tensor/pytorch_backend.py
  pyhf/tensor/tensorflow_backend.py
  tests/test_backend_consistency.py
  tests/test_notebooks.py
  tests/test_tensor.py
Labels: enhancement

#151 Install pyhf from master to get notebooks to run on binder
  binder/environment.yml
  binder/postBuild
Labels: enhancement

#101 Install PyTorch with pip
  .travis.yml
  setup.py
Labels: enhancement

#164 Return CLs instead of 1/CLs
  docs/examples/notebooks/ShapeFactor.ipynb
  docs/examples/notebooks/StatError.ipynb
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/examples/notebooks/histogrammar.ipynb
  docs/examples/notebooks/histosys.ipynb
  docs/examples/notebooks/importxml.ipynb
  docs/examples/notebooks/multiBinPois.ipynb
  docs/examples/notebooks/multichannel-coupled-histo.ipynb
  docs/examples/notebooks/multichannel-coupled-normsys.ipynb
  docs/examples/notebooks/multichannel-normsys.ipynb
  docs/examples/notebooks/normsys.ipynb
  docs/examples/notebooks/tensorflow-limit.ipynb
  pyhf/__init__.py
  tests/test_validation.py
Labels: enhancement

#167 Fix headings of histogrammar notebook
  docs/examples/notebooks/histogrammar.ipynb
Labels: bug, docs

#172 RECAST example
  docs/examples/notebooks/Recast.ipynb
  setup.py
Labels: docs, enhancement

#176 better default options
  pyhf/__init__.py
Labels: enhancement

#175 Add Binder example notebook to docs examples
  docs/conf.py
  docs/examples.rst
Labels: docs, enhancement
