Repository scikit-hep/pyhf, pull requests merged in 2018-08, with the labels that each got.

#182 add bib for adding talks to documentation
  docs/bib/talks.bib
  docs/conf.py
  docs/index.rst
  docs/talks.rst
  setup.py
Labels: docs

#183 bugfix: docs duplicated methods
  docs/_templates/modifierclass.rst
  docs/api.rst
Labels: bug, docs

#186 fix up some of the package versioning. add docs on development installation
  .travis.yml
  docs/development.rst
  docs/index.rst
  setup.py
Labels: docs, enhancement

#190 Add MANIFEST.in and ship spec.json as pkg resource
  MANIFEST.in
  pyhf/data/spec.json
  tests/__init__.py
  tests/test_import.py
  tests/test_pdf.py
  tests/test_validation.py
  validation/spec.json
Labels: enhancement

#193 Reorganize/clean up init file, rename hfpdf, update API docs
  docs/api.rst
  docs/examples/notebooks/Recast.ipynb
  docs/examples/notebooks/ShapeFactor.ipynb
  docs/examples/notebooks/StatError.ipynb
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/examples/notebooks/example-mxnet.ipynb
  docs/examples/notebooks/example-tensorflow.ipynb
  docs/examples/notebooks/histogrammar.ipynb
  docs/examples/notebooks/histosys-pytorch.ipynb
  docs/examples/notebooks/histosys.ipynb
  docs/examples/notebooks/importxml.ipynb
  docs/examples/notebooks/multiBinPois.ipynb
  docs/examples/notebooks/multichannel-coupled-histo.ipynb
  docs/examples/notebooks/multichannel-coupled-normsys.ipynb
  docs/examples/notebooks/multichannel-normsys.ipynb
  docs/examples/notebooks/normsys.ipynb
  docs/examples/notebooks/pytorch_tests_onoff.ipynb
  docs/examples/notebooks/tensorflow-limit.ipynb
  pyhf/__init__.py
  pyhf/pdf.py
  pyhf/simplemodels.py
  pyhf/utils.py
  tests/test_backend_consistency.py
  tests/test_import.py
  tests/test_optim.py
  tests/test_pdf.py
  tests/test_schema.py
  tests/test_tensor.py
  tests/test_validation.py
Labels: enhancement

#194 fix benchmark tests
  tests/benchmarks/test_benchmark.py
Labels: bug

#197 Feature: command line parse xml
  pyhf/commandline.py
  pyhf/readxml.py
  setup.py
  tests/test_scripts.py
Labels: enhancement

#213 Update issue templates using GitHub template builder
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Feature-Request.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: docs, enhancement

#215 Add hello world example and check to tests
  .travis.yml
  README.md
  docs/examples.rst
  docs/examples/notebooks/hello-world.ipynb
  tests/test_notebooks.py
Labels: docs, enhancement

#221 Feature: specify a modifier's pdf type
  pyhf/modifiers/__init__.py
  pyhf/modifiers/histosys.py
  pyhf/modifiers/normsys.py
  pyhf/modifiers/shapesys.py
  pyhf/modifiers/staterror.py
  tests/test_modifiers.py
Labels: enhancement
