Repository scikit-hep/pyhf, pull requests merged in 2018-11, with the labels that each got.

#354 Enable shared nuisance parameters over modifier types
  pyhf/modifiers/histosys.py
  pyhf/modifiers/normfactor.py
  pyhf/modifiers/normsys.py
  pyhf/modifiers/shapefactor.py
  pyhf/modifiers/shapesys.py
  pyhf/modifiers/staterror.py
  pyhf/paramsets.py
  pyhf/pdf.py
Labels: enhancement

#356 Allow for parameter configuration from the spec
  pyhf/data/spec.json
  pyhf/modifiers/__init__.py
  pyhf/modifiers/histosys.py
  pyhf/modifiers/normfactor.py
  pyhf/modifiers/normsys.py
  pyhf/modifiers/shapefactor.py
  pyhf/modifiers/shapesys.py
  pyhf/modifiers/staterror.py
  pyhf/paramsets.py
  pyhf/pdf.py
  tests/test_pdf.py
  tests/test_schema.py
Labels: enhancement

#365 adding cache dictionary to open root files only once in readxml
  pyhf/commandline.py
  pyhf/readxml.py
  setup.py
  tests/test_import.py
Labels: enhancement

#352 Add luminosity uncertainty calculations
  README.md
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  pyhf/commandline.py
  pyhf/data/spec.json
  pyhf/modifiers/__init__.py
  pyhf/modifiers/lumi.py
  pyhf/paramsets.py
  pyhf/pdf.py
  pyhf/readxml.py
  tests/test_import.py
  tests/test_pdf.py
  tests/test_validation.py
Labels: enhancement

#373 Fix location of lumi uncertainty completion in readme
  README.md
Labels: docs

#374 only run coveralls after python3.6 testing
  .travis.yml
Labels: bug

#375 Get the coveralls working again (really, really)
  .travis.yml
Labels: bug
