Repository scikit-hep/pyhf, pull requests merged in 2019-02, with the labels that each got.

#400 Add supported Python versions badge
  README.md
Labels: docs

#401 Update launch Binder badge to new default design
  README.md
  docs/examples.rst
Labels: Binder, docs

#408 Fix URL in readme to point from lukasheinrich fork to main diana-hep repo
  README.md
Labels: docs

#409 Add Bash script to guard max time return value for Binder build
  .travis.yml
  binder/trigger_binder.sh
Labels: Binder, docs

#412 Add Python 3.7 to CI testing
  .travis.yml
  setup.py
Labels: enhancement

#402 add support for shapesys import from xml
  pyhf/readxml.py
  tests/test_import.py
  validation/xmlimport_input3/config/examples/HistFactorySchema.dtd
  validation/xmlimport_input3/config/examples/example_ShapeSys.xml
  validation/xmlimport_input3/config/examples/example_ShapeSys_channel.xml
  validation/xmlimport_input3/data/ShapeSys.root
Labels: enhancement
