Repository scikit-hep/pyhf, pull requests merged in 2019-04, with the labels that each got.

#426 Feature: json2xml (XML+ROOT exporting)
  pyhf/commandline.py
  pyhf/readxml.py
  pyhf/writexml.py
  tests/test_export.py
  tests/test_scripts.py
  tests/test_validation.py
Labels: enhancement

#429 Add test deploy to TestPyPI
  .travis.yml
Labels: docs, enhancement, tests

#430 xmlimport to xmlio, update docs on xml I/O functionality
  docs/examples.rst
  docs/examples/notebooks/XML_ImportExport.ipynb
  docs/installation.rst
  pyhf/commandline.py
  setup.py
  tests/test_notebooks.py
Labels: docs

#436 Finish adding deploy testing with TestPyPI
  .git_archival.txt
  .gitattributes
  .travis.yml
  setup.cfg
  setup.py
Labels: docs, enhancement, tests

#437 Use GitHub hosted images as src target to support PyPI render
  README.md
Labels: docs

#438 Use consistent column alignment in Markdown tables
  README.md
Labels: docs

#440 Workspace specification created, specifications split up
  MANIFEST.in
  docs/api.rst
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  pyhf/__init__.py
  pyhf/commandline.py
  pyhf/data/defs.json
  pyhf/data/measurement.json
  pyhf/data/model.json
  pyhf/data/workspace.json
  pyhf/pdf.py
  pyhf/readxml.py
  pyhf/utils.py
  pyhf/writexml.py
  tests/test_import.py
  tests/test_schema.py
  tests/test_scripts.py
  tests/test_utils.py
  tests/test_validation.py
  tests/test_workspace.py
Labels: enhancement

#444 Move writexml into the json2xml as uproot not required for pyhf usage
  pyhf/commandline.py
Labels: bug

#448 Add ACAT 2019 poster to talks page
  docs/bib/posters.bib
  docs/bib/talks.bib
  docs/talks.rst
Labels: docs

#450 Apply black
  pyhf/utils.py
Labels: bug, docs

#455 Use --no-use-pep517 flag for editable mode with pyproject.toml
  .travis.yml
  docs/development.rst
  pyproject.toml
Labels: bug, docs, enhancement

#452 Add /schemas to documentation
  MANIFEST.in
  docs/conf.py
  docs/schemas
  pyhf/schemas/HistFactorySchema.dtd
  pyhf/schemas/defs.json
  pyhf/schemas/measurement.json
  pyhf/schemas/model.json
  pyhf/schemas/workspace.json
  pyhf/utils.py
  pyhf/writexml.py
Labels: docs

#457 Use papermill versions compatible with v1.0 and add scrapbook
  docs/examples/notebooks/multiBinPois.ipynb
  setup.py
  tests/test_notebooks.py
Labels: tests

#458 Fix schema publishing to docs
  docs/Makefile
  docs/conf.py
  docs/schemas
Labels: docs

#454 Add case 4 of the piecewise interpolator
  docs/api.rst
  pyhf/interpolators/__init__.py
  pyhf/interpolators/code4p.py
  pyhf/interpolators/codex.py
Labels: enhancement
