Repository scikit-hep/pyhf, pull requests merged in 2019-12, with the labels that each got.

#653 feat: expand API to enable pull/impact plots
  docs/examples/notebooks/ImpactPlot.ipynb
  docs/examples/notebooks/pullplot.ipynb
  src/pyhf/optimize/autodiff.py
  src/pyhf/optimize/opt_minuit.py
  src/pyhf/optimize/opt_pytorch.py
  src/pyhf/optimize/opt_scipy.py
  src/pyhf/optimize/opt_tflow.py
  src/pyhf/parameters/paramsets.py
  tests/test_notebooks.py
  tests/test_paramsets.py
Labels: API, docs

#617 feat: pyhf spec CLI
  docs/_templates/modifierclass.rst
  docs/api.rst
  docs/cli.rst
  docs/conf.py
  docs/index.rst
  setup.py
  src/pyhf/cli/cli.py
  src/pyhf/cli/spec.py
  src/pyhf/exceptions/__init__.py
  src/pyhf/schemas/1.0.0/model.json
  src/pyhf/schemas/1.0.0/workspace.json
  src/pyhf/workspace.py
  tests/test_schema.py
  tests/test_scripts.py
  tests/test_workspace.py
Labels: API, docs, feat/enhancement

#588 ci: Use pydocstyle
  .github/workflows/ci.yml
  README.md
  src/pyhf/pdf.py
Labels: CI, tests

#664 ci: Pin GitHub Actions release versions to stable tags
  .github/workflows/ci.yml
  .github/workflows/merged.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
Labels: CI, fix

#665 docs: Use Sphinx cross-referencing '~' syntax to dynamically link the codebase
  src/pyhf/utils.py
Labels: docs

#534 feat: Add backend option to pyhf CLI
  docs/faq.rst
  src/pyhf/cli/stats.py
  src/pyhf/utils.py
  tests/test_scripts.py
Labels: API, feat/enhancement

#666 feat: normfactor import/export parameter configuration
  src/pyhf/readxml.py
  src/pyhf/writexml.py
  tests/test_export.py
  tests/test_import.py
Labels: feat/enhancement, fix

#669 docs: Update StatisticalAnalysis notebook to use workspace more
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
Labels: docs

#675 ci: Migrate Python 2.7 testing from Travis CI to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: CI

#531 refactor: Create infer subpackage to hold our statistics code
  .bumpversion.cfg
  README.md
  docs/api.rst
  docs/conf.py
  docs/examples/notebooks/ImpactPlot.ipynb
  docs/examples/notebooks/Recast.ipynb
  docs/examples/notebooks/ShapeFactor.ipynb
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/examples/notebooks/binderexample/Untitled.ipynb
  docs/examples/notebooks/hello-world.ipynb
  docs/examples/notebooks/multiBinPois.ipynb
  docs/examples/notebooks/multichannel-coupled-histo.ipynb
  docs/examples/notebooks/pullplot.ipynb
  docs/governance/ROADMAP.md
  setup.py
  src/pyhf/__init__.py
  src/pyhf/cli/__init__.py
  src/pyhf/cli/cli.py
  src/pyhf/cli/infer.py
  src/pyhf/infer/__init__.py
  src/pyhf/infer/test_statistics.py
  src/pyhf/infer/utils.py
  src/pyhf/utils.py
  src/pyhf/version.py
  tests/benchmarks/test_benchmark.py
  tests/test_backend_consistency.py
  tests/test_infer.py
  tests/test_optim.py
  tests/test_public_api.py
  tests/test_regression.py
  tests/test_scripts.py
  tests/test_utils.py
  tests/test_validation.py
Labels: bumpversion/minor, feat/enhancement, refactor

#677 docs: Rename statistics to inference in API key
  README.md
  docs/api.rst
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/talks.rst
Labels: docs

#676 docs: make all warnings errors, and fix all warnings
  .bumpversion.cfg
  .github/workflows/ci.yml
  .github/workflows/publish-package.yml
  README.md
  docs/conf.py
  docs/examples.rst
  docs/exts/xref.py
  docs/governance/ROADMAP.md
  docs/index.rst
  docs/installation.rst
  docs/intro.rst
  docs/learn.rst
  docs/likelihood.rst
  docs/talks.rst
  pytest.ini
  setup.cfg
  setup.py
  src/pyhf/infer/__init__.py
  src/pyhf/infer/test_statistics.py
  src/pyhf/infer/utils.py
Labels: docs

#679 ci: use personal access token for gh-pages deployment
  .github/workflows/ci.yml
Labels: CI

#678 docs: Add ATLAS likelihood PUB note to use citations
  docs/bib/use_citations.bib
Labels: docs

#680 fix: Add git to Docker image during build to avoid setuptools-scm error
  docker/Dockerfile
Labels: build, fix

#684 ci: Add test build of the Docker image to the CI
  .github/workflows/ci.yml
Labels: CI

#685 refactor: Create 'backends' extra
  .github/workflows/ci.yml
  .readthedocs.yml
  docs/conf.py
  docs/installation.rst
  setup.py
Labels: CI, docs, refactor

#683 docs: add babel to describe HistFitter to pyhf workflow
  docs/babel.rst
  docs/index.rst
Labels: docs

#672 feat: Add string alias option for setting tensorlib in set_backend
  docs/examples/notebooks/ImpactPlot.ipynb
  docs/examples/notebooks/pullplot.ipynb
  src/pyhf/__init__.py
  src/pyhf/exceptions/__init__.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/test_backend_consistency.py
  tests/test_public_api.py
Labels: API, feat/enhancement, tests

#689 feat: Bump version: 0.3.0 → 0.3.1
  .bumpversion.cfg
  setup.py
  src/pyhf/version.py
Labels: API, bumpversion/patch

#688 chore: Remove top level 'examples' dir
  docs/examples/json/2-bin_1-channel.json
  docs/likelihood.rst
  examples/experiments/edwardpyhf.ipynb
  tests/test_examples.py
Labels: chore, docs

#693 ci: Add Codecov threshold tolerance
  codecov.yml
  pyproject.toml
Labels: CI

#697 ci: Use Python 3 scipy Alpine image for base Docker image
  docker/Dockerfile
Labels: CI, build

#700 feat: Add ENTRYPOINT to pyhf Docker image
  docker/Dockerfile
Labels: feat/enhancement

#698 docs: add docstrings for src/pyhf/infer
  src/pyhf/infer/__init__.py
  src/pyhf/infer/utils.py
Labels: docs

#699 docs: Add Altair example notebook
  docs/examples/notebooks/altair.ipynb
Labels: docs

#706 fix: Add Altair dependency to Binder postBuild
  binder/postBuild
Labels: Binder, fix

#702 docs: Add docstrings for interpolators
  .github/workflows/ci.yml
  src/pyhf/interpolators/__init__.py
  src/pyhf/interpolators/code0.py
  src/pyhf/interpolators/code1.py
  src/pyhf/interpolators/code2.py
  src/pyhf/interpolators/code4.py
  src/pyhf/interpolators/code4p.py
Labels: docs

#701 feat: double precision for ML backends
  src/pyhf/cli/infer.py
  src/pyhf/optimize/opt_tflow.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/conftest.py
Labels: feat/enhancement

#650 ci: workflow that runs bumpversion and pushes when issue filed
  .github/workflows/tag.yml
Labels: CI

#690 refactor: MLE API
  .github/workflows/ci.yml
  docs/api.rst
  docs/examples/notebooks/ImpactPlot.ipynb
  docs/examples/notebooks/ShapeFactor.ipynb
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/examples/notebooks/multiBinPois.ipynb
  docs/examples/notebooks/multichannel-coupled-histo.ipynb
  docs/examples/notebooks/pullplot.ipynb
  src/pyhf/infer/mle.py
  src/pyhf/infer/test_statistics.py
  src/pyhf/infer/utils.py
  src/pyhf/optimize/__init__.py
  src/pyhf/optimize/autodiff.py
  src/pyhf/optimize/opt_minuit.py
  src/pyhf/optimize/opt_pytorch.py
  src/pyhf/optimize/opt_scipy.py
  src/pyhf/optimize/opt_tflow.py
  tests/test_optim.py
Labels: API, refactor

#694 feat: Add contrib module
  .github/workflows/ci.yml
  CONTRIBUTING.md
  docs/examples/notebooks/Recast.ipynb
  setup.py
  src/pyhf/contrib/__init__.py
  src/pyhf/contrib/viz/__init__.py
  src/pyhf/contrib/viz/brazil.py
  tests/contrib/baseline/test_brazil.png
  tests/contrib/hypotestresults.json
  tests/contrib/test_viz.py
Labels: CI, docs, feat/enhancement, tests

#711 fix: Correct order of Codecov reporting in CI
  .github/workflows/ci.yml
Labels: CI, fix

#710 ci: Use lowercase OS names to match API
  .github/workflows/ci.yml
  .github/workflows/release_tests.yml
Labels: CI
