Repository scikit-hep/pyhf, pull requests merged in 2019-11, with the labels that each got.

#624 docs: Add talks, seminars, and tutorials up through October 2019
  docs/bib/talks.bib
  docs/bib/tutorials.bib
  docs/talks.rst
Labels: docs

#626 revert: Use TensorFlow Probability release compatible with TensorFlow v1.15
  setup.py
Labels: revert

#535 feat: Add 'conditional' method to tensorlib API
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/test_tensor.py
Labels: API, feat/enhancement

#629 ci: Migrate docs deployment to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: CI, docs

#628 ci: Use GitHub Actions os API
  .github/workflows/ci.yml
Labels: CI

#634 ci: Remove redundant check-manifest
  .github/workflows/ci.yml
Labels: CI

#632 chore: Use DOI endpoint API for sbottom likelihood
  tests/test_regression.py
Labels: CI, chore

#637 chore: Use python3 for precommit language version
  .pre-commit-config.yaml
Labels: chore

#625 feat: Add autodiff driven SciPy optimizer
  src/pyhf/interpolators/code4p.py
  src/pyhf/optimize/autodiff.py
  src/pyhf/optimize/opt_pytorch.py
  src/pyhf/optimize/opt_tflow.py
  src/pyhf/pdf.py
Labels: feat/enhancement

#638 ci: Migrate publishing from Travis CI to GitHub Actions
  .github/workflows/publish-package.yml
  .travis.yml
  README.md
  docs/development.rst
  docs/governance/ROADMAP.md
  setup.py
Labels: CI, build, docs

#639 fix: Add build-system to pyproject.toml
  .github/workflows/publish-package.yml
  pyproject.toml
Labels: CI, build

#640 fix: Correct reference check in GitHub Actions publish to TestPyPI step
  .github/workflows/publish-package.yml
  setup.py
Labels: CI, fix

#643 chore: Migrate from diana-hep GitHub org to scikit-hep
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/Bug-Fix.md
  .github/PULL_REQUEST_TEMPLATE/Feature.md
  .github/workflows/merged.yml
  .github/workflows/publish-package.yml
  CONTRIBUTING.md
  README.md
  docs/_templates/modifierclass.rst
  docs/bib/docs.bib
  docs/conf.py
  docs/development.rst
  docs/examples.rst
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/faq.rst
  docs/governance/ROADMAP.md
  docs/index.rst
  docs/installation.rst
  docs/likelihood.rst
  setup.py
  src/pyhf/schemas/1.0.0/defs.json
  src/pyhf/schemas/1.0.0/measurement.json
  src/pyhf/schemas/1.0.0/model.json
  src/pyhf/schemas/1.0.0/workspace.json
  src/pyhf/utils.py
Labels: chore

#645 docs: Bump version: 0.2.1 → 0.2.2
  .bumpversion.cfg
  docs/conf.py
  setup.py
  src/pyhf/version.py
Labels: docs

#646 fix: Promote check on PR merge to job level
  .github/workflows/merged.yml
Labels: CI, fix

#644 docs: Add presentations for November 2019
  README.md
  docs/bib/posters.bib
  docs/bib/talks.bib
  docs/governance/ROADMAP.md
Labels: docs

#611 test: Add public API canary tests to CI and nightly tests for current PyPI release
  .github/workflows/release_tests.yml
  .gitignore
  tests/conftest.py
  tests/test_public_api.py
Labels: CI, tests

#648 refactor: Add better segmented environments
  .github/workflows/ci.yml
  setup.py
Labels: CI, build, fix, refactor

#649 refactor: Reorder mega mods to be indexed first by modifier then by sample
  src/pyhf/modifiers/histosys.py
  src/pyhf/modifiers/lumi.py
  src/pyhf/modifiers/normfactor.py
  src/pyhf/modifiers/normsys.py
  src/pyhf/modifiers/shapefactor.py
  src/pyhf/modifiers/shapesys.py
  src/pyhf/modifiers/staterror.py
  src/pyhf/pdf.py
  tests/test_combined_modifiers.py
Labels: refactor

#652 fix: Add missing pytest dependencies to Current Release tests
  .github/workflows/release_tests.yml
Labels: CI, fix

#655 docs: Add pyhf logo to top of README
  README.md
  docs/_static/img/pyhf-logo.png
Labels: docs

#657 feat: Add Channel summary mixin, JSON-serializable workspace object
  src/pyhf/commandline.py
  src/pyhf/mixins.py
  src/pyhf/pdf.py
  src/pyhf/workspace.py
  tests/test_mixins.py
  tests/test_workspace.py
Labels: feat/enhancement, refactor

#656 refactor: Use a CLI subpackage
  setup.py
  src/pyhf/cli/__init__.py
  src/pyhf/cli/cli.py
  src/pyhf/cli/rootio.py
  src/pyhf/cli/spec.py
  src/pyhf/cli/stats.py
  src/pyhf/commandline.py
Labels: refactor
