Repository scikit-hep/pyhf, pull requests merged in 2019-10, with the labels that each got.

#592 fix: Add upper bound on TensorFlow Probability to avoid TensorFlow compatibility conflict
  setup.py
Labels: fix

#590 ci: Test example notebooks separately
  .github/workflows/ci.yml
Labels: CI

#597 ci: Use 'python-version' keyword in GitHub Actions
  .github/workflows/ci.yml
Labels: CI, fix

#599 ci: Drop Python 2.7 testing of notebooks
  .travis.yml
Labels: CI, tests

#598 ci: Use Codecov GitHub Action to report coverage
  .coveragerc
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  README.md
  pytest.ini
  setup.py
Labels: CI, build

#584 ci: Use Travis CI only for Python 2.7 testing and releases
  .github/workflows/ci.yml
  .github/workflows/merged.yml
  .travis.yml
Labels: CI

#602 fix: Address LGTM division alert
  src/pyhf/commandline.py
  src/pyhf/interpolators/code4.py
Labels: fix

#582 perf: Effectively remove the use of self.astensor() in tensor backend calls
  src/pyhf/interpolators/code0.py
  src/pyhf/interpolators/code1.py
  src/pyhf/interpolators/code2.py
  src/pyhf/interpolators/code4.py
  src/pyhf/modifiers/histosys.py
  src/pyhf/modifiers/lumi.py
  src/pyhf/modifiers/normfactor.py
  src/pyhf/modifiers/normsys.py
  src/pyhf/modifiers/shapefactor.py
  src/pyhf/modifiers/shapesys.py
  src/pyhf/modifiers/staterror.py
  src/pyhf/tensor/common.py
  src/pyhf/tensor/mxnet_backend.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  src/pyhf/utils.py
  tests/conftest.py
  tests/test_combined_modifiers.py
  tests/test_probability.py
  tests/test_tensor.py
Labels: perf

#596 improvement: API of Simultaneous to duck-type as list
  .gitignore
  src/pyhf/pdf.py
  src/pyhf/probability.py
  tests/test_probability.py
Labels: API, feat/enhancement, refactor

#589 docs: Use consistent style in docstrings
  .github/workflows/ci.yml
  setup.py
  src/pyhf/probability.py
  src/pyhf/tensor/tensorflow_backend.py
Labels: docs, fix

#615 docs: Add copyright holders to license
  LICENSE
  setup.py
Labels: docs

#607 revert: Drop support for MXNet
  README.md
  docs/api.rst
  docs/examples.rst
  docs/examples/notebooks/example-mxnet.ipynb
  docs/examples/notebooks/histosys-pytorch.ipynb
  docs/installation.rst
  setup.py
  src/pyhf/__init__.py
  src/pyhf/tensor/__init__.py
  src/pyhf/tensor/mxnet_backend.py
  tests/benchmarks/test_benchmark.py
  tests/conftest.py
  tests/test_backend_consistency.py
  tests/test_combined_modifiers.py
  tests/test_init.py
  tests/test_interpolate.py
  tests/test_optim.py
  tests/test_pdf.py
  tests/test_tensor.py
Labels: revert

#623 test: Add regression test on ATLAS sbottom public likelihood
  docs/governance/ROADMAP.md
  tests/test_regression.py
  tests/test_validation.py
Labels: tests
