Repository scikit-hep/pyhf, pull requests merged in 2019-09, with the labels that each got.

#538 Add 'tile' method to tensorlib API
  src/pyhf/tensor/mxnet_backend.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/test_tensor.py
Labels: API, enhancement

#519 Add ParamViewer class
  src/pyhf/constraints.py
  src/pyhf/modifiers/histosys.py
  src/pyhf/modifiers/lumi.py
  src/pyhf/modifiers/normfactor.py
  src/pyhf/modifiers/normsys.py
  src/pyhf/modifiers/shapefactor.py
  src/pyhf/modifiers/shapesys.py
  src/pyhf/modifiers/staterror.py
  src/pyhf/paramsets.py
  src/pyhf/paramview.py
  src/pyhf/pdf.py
  tests/test_combined_modifiers.py
  tests/test_constraints.py
  tests/test_paramviewer.py
Labels: enhancement, optimization

#544 Add Git pre-commit hook install to CONTRIBUTING
  CONTRIBUTING.md
  docs/development.rst
Labels: docs

#546 Enable full batch evaluation
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  src/pyhf/paramsets.py
  src/pyhf/pdf.py
  src/pyhf/simplemodels.py
  tests/test_pdf.py
  tests/test_validation.py
Labels: API, enhancement, optimization

#549 Rewrite Model into PDF composition of MainModel and ConstrainedModel
  src/pyhf/pdf.py
Labels: research

#552 Add GitHub Actions CI status badge to README
  README.md
Labels: CI, docs

#551 Add probability module
  docs/api.rst
  src/pyhf/constraints.py
  src/pyhf/pdf.py
  src/pyhf/probability.py
  tests/test_probability.py
Labels: API, enhancement

#565 feat: add semantic PR
  .github/semantic.yml
  CONTRIBUTING.md
Labels: enhancement

#564 fix: 1 bin lumi validation test
  src/pyhf/exceptions/__init__.py
  src/pyhf/pdf.py
  tests/test_pdf.py
  tests/test_validation.py
Labels: bug, tests

#553 feat: Simultaneous pdf class
  src/pyhf/constraints.py
  src/pyhf/pdf.py
  src/pyhf/probability.py
  src/pyhf/tensor/common.py
  src/pyhf/tensor/pytorch_backend.py
Labels: enhancement

#571 fix: Avoid benchmark timeout in CI systems
  .github/workflows/ci.yml
  .travis.yml
  tests/conftest.py
Labels: CI, bug, tests

#570 fix: Unhide test_normal by renaming redundant name to test_independent
  tests/test_probability.py
Labels: bug, tests

#578 fix: Correct error in invert_interval in Binder example notebook
  docs/examples/notebooks/ShapeFactor.ipynb
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/examples/notebooks/multiBinPois.ipynb
  docs/examples/notebooks/multichannel-coupled-histo.ipynb
Labels: bug, docs

#567 docs: Add roadmap document for 2019 into 2020
  docs/governance/ROADMAP.md
Labels: docs

#581 revert: Remove skip of NumPy+Minuit 200 bin benchmark
  .github/workflows/ci.yml
  .travis.yml
Labels: CI, revert, tests

#585 ci: Add MacOS testing environment to GitHub Actions CI
  .github/workflows/ci.yml
Labels: CI

#574 fix: Correct warnings raised by LGTM scan
  src/pyhf/pdf.py
  src/pyhf/tensor/tensorflow_backend.py
  validation/manualonoff_roofit/onoff.py
Labels: fix

#558 feat: Add toy sampling
  docs/api.rst
  docs/governance/ROADMAP.md
  src/pyhf/constraints.py
  src/pyhf/parameters/paramsets.py
  src/pyhf/pdf.py
  src/pyhf/probability.py
  src/pyhf/tensor/common.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/test_probability.py
  tests/test_toys.py
Labels: feat/enhancement
