Repository scikit-hep/pyhf, pull requests merged in 2019-05, with the labels that each got.

#431 fix divide to only divide non-zero pieces.
  pyhf/writexml.py
  tests/test_export.py
Labels: bug, follow up

#460 Add assertion and check for sample size consistency
  pyhf/pdf.py
  tests/test_pdf.py
Labels: enhancement

#403 Add configurable optimizer (and options) through pyhf cls CLI
  pyhf/commandline.py
  pyhf/exceptions/__init__.py
  pyhf/optimize/__init__.py
  pyhf/optimize/opt_scipy.py
  pyhf/optimize/opt_tflow.py
  pyhf/utils.py
  setup.py
  tests/test_optim.py
  tests/test_scripts.py
  tests/test_utils.py
Labels: enhancement

#464 Don't cache pip installs for Python 3.6 in Travis to avoid memory EnvironmentError
  .travis.yml
Labels: CI, bug

#461 Remove print function in CLI
  pyhf/commandline.py
Labels: bug

#463 Remove editable flag for Binder to avoid PEP 517 issue with pip
  binder/postBuild
Labels: Binder, bug

#470 Add guard for Trusty build environments to prevent memory issues
  .travis.yml
Labels: CI, bug

#462 Add May 2019 Joint Machine Learning and Stats Fora Meeting talk
  docs/bib/talks.bib
Labels: docs

#471 Remove use of --no-use-pep517 flag from pip install with pip v19.1.1+
  .travis.yml
  docs/development.rst
Labels: CI, docs, enhancement

#472 Add semantic-versioning to JSON schemas
  pyhf/pdf.py
  pyhf/readxml.py
  pyhf/schemas/1.0.0/defs.json
  pyhf/schemas/1.0.0/measurement.json
  pyhf/schemas/1.0.0/model.json
  pyhf/schemas/1.0.0/workspace.json
  pyhf/utils.py
Labels: enhancement, schema and spec

#475 Add SUSY 2019 conference talk
  docs/bib/talks.bib
Labels: docs
