Repository scikit-hep/pyhf, pull requests merged in 2020-07, with the labels that each got.

#910 feat: Add precision information to tensorlib backends
  src/pyhf/tensor/jax_backend.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/test_tensor.py
Labels: API, feat/enhancement

#915 fix: Disallow cloudpickle v1.5.0 in 'tensorflow' extra
  setup.py
Labels: bumpversion/patch, fix

#917 ci: Run Docker test on tag pushes to avoid breaking CI
  .github/workflows/ci.yml
Labels: CI

#914 feat: Single precision setting for backends
  src/pyhf/cli/infer.py
  src/pyhf/tensor/jax_backend.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/conftest.py
  tests/test_tensor.py
Labels: API, feat/enhancement

#922 fix: Set backend global states correctly
  src/pyhf/__init__.py
  src/pyhf/tensor/jax_backend.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/test_public_api.py
  tests/test_tensor.py
Labels: fix, tests

#924 revert: Rollback constraints on cloudpickle given TFP v0.10.1 release
  setup.py
Labels: build, revert

#902 fix: Change p-value calculation from 1-cdf(x) to cdf(-x)
  src/pyhf/infer/calculators.py
  src/pyhf/tensor/pytorch_backend.py
  tests/test_infer.py
  tests/test_validation.py
Labels: fix, tests

#930 chore: Future proof release against uproot4 API changes
  setup.py
Labels: build, chore

#933 docs: Unrestrict Sphinx from v3.0.X releases
  setup.py
Labels: docs, fix

#931 docs: Add TRExFitter babel translation
  docs/babel.rst
Labels: docs

#938 docs: Add examples of good contributions to CONTRIBUTING
  CONTRIBUTING.md
Labels: docs

#919 feat: Enable shell completion
  setup.py
  src/pyhf/cli/__init__.py
  src/pyhf/cli/cli.py
  src/pyhf/cli/complete.py
  tests/test_cli.py
Labels: CLI, feat/enhancement, tests

#941 docs: Fix CLs wrapping and add shorter URL
  src/pyhf/cli/infer.py
Labels: docs, fix

#937 docs: Add hepdata_like model API to docs
  docs/api.rst
  src/pyhf/simplemodels.py
Labels: docs

#950 feat: support no POI
  docs/governance/ROADMAP.rst
  src/pyhf/exceptions/__init__.py
  src/pyhf/infer/mle.py
  src/pyhf/infer/test_statistics.py
  src/pyhf/pdf.py
  tests/test_pdf.py
Labels: API, feat/enhancement

#960 docs: Clarify objective function in infer.mle
  src/pyhf/infer/mle.py
Labels: docs

#961 docs: Clarify role of return_fitted_val kwarg for fit and fixed_poi_fit
  src/pyhf/infer/mle.py
Labels: docs

#962 refactor: Use AsymptoticTestStatDistribution.expected_value API in hypotest for better integration
  src/pyhf/infer/__init__.py
  src/pyhf/infer/calculators.py
Labels: refactor

#968 fix: Protect against missing JAX imports
  src/pyhf/tensor/__init__.py
  tests/test_init.py
Labels: fix

#967 docs: Add 2020 ATLAS Induction Day and PyHEP 2020 tutorials
  docs/bib/tutorials.bib
Labels: docs

#975 chore: Set minimum version for iminuit to v1.4.3
  setup.py
Labels: chore

#976 fix: Enable jax.np.stack for axis !=0
  src/pyhf/tensor/jax_backend.py
  tests/test_tensor.py
Labels: feat/enhancement, tests

#985 docs: Replace optimizer table with list
  README.rst
Labels: docs

#983 feat: Add precision setting string API to set_backend
  src/pyhf/__init__.py
  src/pyhf/cli/infer.py
  tests/test_jit.py
  tests/test_public_api.py
Labels: API, feat/enhancement

#972 revert: Allow 0-dimensional shape tensors
  src/pyhf/infer/mle.py
  src/pyhf/infer/test_statistics.py
  src/pyhf/optimize/opt_numpy.py
  src/pyhf/optimize/opt_pytorch.py
  src/pyhf/optimize/opt_tflow.py
  src/pyhf/tensor/jax_backend.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/test_backend_consistency.py
  tests/test_constraints.py
  tests/test_infer.py
  tests/test_optim.py
  tests/test_tensor.py
Labels: bumpversion/minor, docs, revert, tests

#991 fix: stitch_pars bug in stitching values other than fixed values
  src/pyhf/optimize/common.py
  tests/test_optim.py
Labels: fix, tests

#999 build: Restrict TensorFlow to v2.2.X and TensorFlow Probability to v0.10.X
  setup.py
Labels: build, fix

#1000 docs: 1000!
  README.rst
Labels: docs

#996 fix: Clean apt path after apt-get install
  .github/workflows/lint.yml
  .hadolint.yaml
  docker/Dockerfile
  docker/gpu/Dockerfile
Labels: CI, fix, revert

#1003 docs: Add Conda-forge release version badge
  README.rst
Labels: docs

#1010 feat: Add cdf method to AsymptoticTestStatDistribution
  src/pyhf/infer/calculators.py
  tests/test_calculator.py
Labels: feat/enhancement, tests

#1012 docs: Match docstring style format
  src/pyhf/infer/calculators.py
Labels: docs, fix
