Repository scikit-hep/pyhf, pull requests merged in 2020-06, with the labels that each got.

#888 fix: Check if HEAD of origin/master is accessible from latest tag
  .github/workflows/publish-package.yml
Labels: CI, deployment, fix

#889 docs: Add 1Lbb hepdata likelihood record
  docs/bib/HEPData_likelihoods.bib
Labels: docs

#893 ci: Use Python 3.8 in all steps of publishing distributions
  .github/workflows/publish-package.yml
Labels: CI, chore, deployment

#898 fix: Keep Sphinx at v3.0.X releases
  setup.py
Labels: docs, fix

#904 fix: Update infer.mle docstrings to match SciPy v1.5.0
  src/pyhf/infer/mle.py
Labels: chore, docs, fix

#903 ci: Separate linting from testing
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/publish-package.yml
  setup.py
Labels: CI, build

#909 ci: Verify build backend is compliant with PEP 517 in publishing workflow
  .github/workflows/publish-package.yml
Labels: CI, deployment
