Repository scikit-hep/pyhf, pull requests merged in 2020-12, with the labels that each got.

#1203 ci: Test only latest Python runtime on MacOS
  .github/workflows/ci.yml
  .github/workflows/release_tests.yml
Labels: CI

#1206 fix: Update JAX DeviceArray type in docstrings for doctest
  src/pyhf/tensor/jax_backend.py
Labels: docs, fix

#1210 feat: Add utility to get software citation and CLI interface
  .bumpversion.cfg
  docs/bib/preferred.bib
  src/pyhf/cli/cli.py
  src/pyhf/data/citation.bib
  src/pyhf/utils.py
  tests/test_scripts.py
  tests/test_utils.py
Labels: API, CLI, docs, feat/enhancement

#1209 chore: Use exc_info in log.error, re-raise last exceptions
  src/pyhf/cli/rootio.py
  src/pyhf/contrib/cli.py
  src/pyhf/contrib/utils.py
  src/pyhf/optimize/mixins.py
  src/pyhf/tensor/jax_backend.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  src/pyhf/workspace.py
Labels: chore

#1217 docs: Link to conda-forge feedstock and link banner to repo
  README.rst
  docs/index.rst
Labels: docs

#1220 fix: Ensure pytest.approx only compares floats
  .github/workflows/dependencies-head.yml
  setup.py
  tests/test_optim.py
Labels: fix, tests

#1227 ci: Uninstall dependencies before installed HEAD versions
  .github/workflows/dependencies-head.yml
Labels: CI, fix

#1218 fix: Control utils.py docstring example with .bumpversion.cfg
  .bumpversion.cfg
  src/pyhf/data/citation.bib
Labels: docs, fix

#1229 build: Use compatible release syntax to give ranges for install_requires
  setup.cfg
Labels: build

#1230 refactor: Clean up docstrings and remove qtilde from hypotest
  src/pyhf/infer/__init__.py
  src/pyhf/infer/calculators.py
Labels: docs, refactor

#1231 feat: Test statistic specified by string instead of using qtilde kwarg
  README.rst
  docs/api.rst
  docs/examples/notebooks/hello-world.ipynb
  docs/examples/notebooks/toys.ipynb
  src/pyhf/cli/infer.py
  src/pyhf/exceptions/__init__.py
  src/pyhf/infer/__init__.py
  src/pyhf/infer/calculators.py
  src/pyhf/infer/intervals.py
  src/pyhf/infer/utils.py
  tests/test_infer.py
  tests/test_regression.py
  tests/test_scripts.py
  tests/test_teststats.py
  tests/test_validation.py
Labels: API, docs, feat/enhancement, refactor
