Repository scikit-hep/pyhf, pull requests merged in 2020-01, with the labels that each got.

#712 feat: change qmu API and remove test_stat return
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/examples/notebooks/hello-world.ipynb
  src/pyhf/infer/__init__.py
  src/pyhf/infer/test_statistics.py
  src/pyhf/infer/utils.py
  tests/benchmarks/test_benchmark.py
  tests/test_backend_consistency.py
  tests/test_infer.py
  tests/test_public_api.py
Labels: API, bumpversion/patch, feat/enhancement

#707 docs: Apply pydocstyle to Workspace
  .github/workflows/ci.yml
  src/pyhf/workspace.py
Labels: docs, tests

#719 docs: Directly link to GitHub project page from docs website
  README.md
Labels: docs

#723 fix: Update nbformat to v4.4 for all tested notebooks
  docs/examples/notebooks/ImpactPlot.ipynb
  docs/examples/notebooks/ShapeFactor.ipynb
  docs/examples/notebooks/XML_ImportExport.ipynb
  docs/examples/notebooks/altair.ipynb
  docs/examples/notebooks/binderexample/StatisticalAnalysis.ipynb
  docs/examples/notebooks/hello-world.ipynb
  docs/examples/notebooks/learn/InterpolationCodes.ipynb
  docs/examples/notebooks/learn/TensorizingInterpolations.ipynb
  docs/examples/notebooks/multiBinPois.ipynb
  docs/examples/notebooks/multichannel-coupled-histo.ipynb
  docs/examples/notebooks/pullplot.ipynb
Labels: fix

#717 refactor: Use multistage Docker build to include only built libraries in Docker image
  .github/workflows/ci.yml
  docker/Dockerfile
Labels: CI, build, refactor

#718 chore: Make tests pass pyflakes
  .github/workflows/ci.yml
  tests/conftest.py
  tests/contrib/test_viz.py
  tests/test_events.py
  tests/test_export.py
  tests/test_import.py
  tests/test_infer.py
  tests/test_interpolate.py
  tests/test_modifiers.py
  tests/test_pdf.py
  tests/test_utils.py
  tests/test_workspace.py
Labels: CI, chore, tests

#541 feat: Migrate to TensorFlow v2.0
  docs/governance/ROADMAP.md
  setup.py
  src/pyhf/__init__.py
  src/pyhf/cli/infer.py
  src/pyhf/optimize/opt_tflow.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/conftest.py
  tests/test_backend_consistency.py
  tests/test_tensor.py
Labels: API, bumpversion/patch, docs, feat/enhancement, tests

#377 feat: Add jax backend
  README.md
  docs/installation.rst
  setup.py
  src/pyhf/__init__.py
  src/pyhf/cli/infer.py
  src/pyhf/optimize/__init__.py
  src/pyhf/optimize/opt_jax.py
  src/pyhf/tensor/__init__.py
  src/pyhf/tensor/jax_backend.py
  tests/conftest.py
  tests/test_backend_consistency.py
  tests/test_optim.py
  tests/test_scripts.py
  tests/test_tensor.py
Labels: bumpversion/patch, feat/enhancement

#724 fix: Correct iminuit optimizer verbose setting typo
  src/pyhf/optimize/opt_minuit.py
Labels: fix

#704 feat: Drop Python 2.7 support
  .github/workflows/ci.yml
  docs/faq.rst
  docs/governance/ROADMAP.md
  docs/installation.rst
  pyproject.toml
  setup.py
  src/pyhf/cli/rootio.py
  src/pyhf/infer/mle.py
  src/pyhf/optimize/opt_minuit.py
  src/pyhf/pdf.py
  tests/test_notebooks.py
  tests/test_scripts.py
Labels: CI, bumpversion/minor, docs, feat/enhancement

#732 docs: cover src/pyhf/contrib and src/pyhf/cli with pydocstest
  .github/workflows/ci.yml
  src/pyhf/cli/__init__.py
  src/pyhf/cli/cli.py
  src/pyhf/cli/infer.py
  src/pyhf/cli/rootio.py
  src/pyhf/cli/spec.py
  src/pyhf/contrib/__init__.py
  src/pyhf/contrib/viz/__init__.py
  src/pyhf/contrib/viz/brazil.py
Labels: docs

#737 chore: Run pyflakes over the full codebase
  .github/workflows/ci.yml
  docs/exts/xref.py
Labels: chore

#745 refactor: rearrange asymptotics
  src/pyhf/infer/utils.py
Labels: refactor

#753 docs: Add Scikit-HEP Project badge to README
  README.md
Labels: docs

#755 chore: Use scikit-hep.org hosted badge SVG
  README.md
Labels: chore, docs

#744 refactor: standalone spec parsing for parameters
  src/pyhf/pdf.py
Labels: refactor

#758 docs: Add preferred BibTeX entry for citation
  .bumpversion.cfg
  README.md
  docs/bib/preferred.bib
  docs/citations.rst
Labels: docs
