Repository scikit-hep/pyhf, pull requests merged in 2020-05, with the labels that each got.

#849 docs: Add docstrings and examples to infer fitting methods
  src/pyhf/infer/__init__.py
  src/pyhf/infer/mle.py
  src/pyhf/infer/test_statistics.py
Labels: docs, fix

#847 feat: Add patchset schema and datadir pytest fixture
  docs/development.rst
  src/pyhf/schemas/1.0.0/defs.json
  src/pyhf/schemas/1.0.0/jsonpatch.json
  src/pyhf/schemas/1.0.0/patchset.json
  tests/conftest.py
  tests/test_schema.py
  tests/test_schema/patchset_bad_empty_patches.json
  tests/test_schema/patchset_bad_invalid_hash.json
  tests/test_schema/patchset_bad_label_pattern.json
  tests/test_schema/patchset_bad_no_description.json
  tests/test_schema/patchset_bad_no_hash.json
  tests/test_schema/patchset_bad_no_labels.json
  tests/test_schema/patchset_bad_no_patch_name.json
  tests/test_schema/patchset_bad_no_patch_values.json
  tests/test_schema/patchset_good.json
  tests/test_schema/patchset_good_no_analysis.json
Labels: docs, feat/enhancement, schema and spec, tests

#647 docs: Improve discussion of publication workflow
  docs/development.rst
Labels: docs

#853 chore: Update papermill to use v2 releases
  setup.py
Labels: chore

#855 fix: Remove dead OVH Binder build endpoint and add GESIS and Turing endpoints
  .github/workflows/merged.yml
Labels: Binder, CI, fix

#852 feat: Add utility for computing object digests ("hashing")
  docs/api.rst
  src/pyhf/cli/cli.py
  src/pyhf/cli/spec.py
  src/pyhf/schemas/1.0.0/defs.json
  src/pyhf/utils.py
  tests/test_schema.py
  tests/test_schema/patchset_bad_empty_patches.json
  tests/test_schema/patchset_bad_invalid_digests.json
  tests/test_schema/patchset_bad_label_pattern.json
  tests/test_schema/patchset_bad_no_description.json
  tests/test_schema/patchset_bad_no_digests.json
  tests/test_schema/patchset_bad_no_labels.json
  tests/test_schema/patchset_bad_no_patch_name.json
  tests/test_schema/patchset_bad_no_patch_values.json
  tests/test_schema/patchset_good.json
  tests/test_schema/patchset_good_no_analysis.json
  tests/test_scripts.py
  tests/test_utils.py
Labels: API, feat/enhancement, schema and spec, tests

#859 docs: Add instructions for installing test releases from TestPyPI
  docs/development.rst
Labels: docs

#860 ci: Add Python 3.8 to tests
  .github/workflows/ci.yml
  .github/workflows/release_tests.yml
  setup.py
Labels: CI

#862 docs: Update keywords, classifiers, and URLs in setup.py
  .pre-commit-config.yaml
  setup.py
Labels: docs

#866 fix: Allow users to set logging level
  src/pyhf/cli/infer.py
  src/pyhf/cli/rootio.py
  src/pyhf/cli/spec.py
  src/pyhf/mixins.py
  src/pyhf/workspace.py
Labels: fix

#868 chore: Update setup-python action to v2
  .github/workflows/ci.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
  .github/workflows/tag.yml
Labels: CI, chore

#873 chore: Migrate metadata and setup options to setup.cfg
  .bumpversion.cfg
  setup.cfg
  setup.py
Labels: chore, packaging

#875 fix: Sanitize double quotes for Tag Creator
  .github/workflows/tag.yml
Labels: CI, fix

#880 ci: Use checkout v2.2.0 fetch-depth option to unshallow all
  .github/workflows/ci.yml
  .github/workflows/publish-package.yml
  .github/workflows/tag.yml
Labels: CI

#796 build: Require minimum SciPy version of v1.4.0
  setup.cfg
Labels: build, bumpversion/patch

#877 docs: Add simple examples for inspect, cls, and digest CLI
  src/pyhf/cli/infer.py
  src/pyhf/cli/spec.py
Labels: docs

#885 fix: Avoid warning of 'app.add_stylesheet() is deprecated'
  docs/conf.py
Labels: docs, fix

#884 fix: Set checkout GHA persist-credentials to false for push to succeed
  .github/workflows/tag.yml
Labels: CI, bumpversion/patch, fix
