Repository scikit-hep/pyhf, pull requests merged in 2020-04, with the labels that each got.

#816 docs: Add JAX to Python API docs
  docs/api.rst
  docs/conf.py
  src/pyhf/__init__.py
  src/pyhf/tensor/jax_backend.py
Labels: docs

#819 docs: Use rST instead of Markdown for README and ROADMAP
  .bumpversion.cfg
  .dockerignore
  .github/workflows/ci.yml
  .github/workflows/release_tests.yml
  README.md
  README.rst
  docs/conf.py
  docs/governance/ROADMAP.md
  docs/governance/ROADMAP.rst
  docs/index.rst
  setup.py
  tests/test_scripts.py
Labels: CI, docs, fix, tests

#825 fix: Replace use of raw directive in README.rst
  .github/workflows/publish-package.yml
  README.rst
  docs/_static/img/hfh_1bin_55_50_7.png
  docs/_static/img/hfh_2_bin_100.0_145.0_100.0_150.0_15.0_20.0_30.0_45.0.png
  docs/_static/img/manual_2_bin_100.0_145.0_100.0_150.0_15.0_20.0_30.0_45.0.png
  docs/_static/img/pyhf-logo-small.png
Labels: CI, docs, fix

#823 chore: Remove redundant install of matplotlib from 'test' extra
  setup.py
Labels: chore

#826 chore: Use GitHub Actions checkout action v2
  .github/workflows/ci.yml
  .github/workflows/merged.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
  .github/workflows/tag.yml
Labels: CI, chore

#827 feat: Add curl to Docker image
  .github/workflows/ci.yml
  docker/Dockerfile
Labels: CI, feat/enhancement

#833 fix: Get full history and all tags for TestPyPI and PyPI publishing workflow
  .github/workflows/publish-package.yml
Labels: CI, build, fix

#834 chore: Update gh-action-pypi-publish to non-alpha release
  .github/workflows/publish-package.yml
Labels: CI, chore

#831 revert: Remove disk space regression hack fix
  .github/workflows/ci.yml
  .github/workflows/release_tests.yml
Labels: CI, revert

#813 feat: Catch unknown kwargs while creating a model
  src/pyhf/pdf.py
  src/pyhf/workspace.py
  tests/test_pdf.py
Labels: fix

#837 feat: Update jsonschema to non-alpha release
  setup.py
Labels: feat/enhancement

#839 fix: Have release versioning work in docs build CI
  .github/workflows/ci.yml
Labels: CI, docs, fix

#838 refactor: Simplify Workspace::get_measurement and harmonize poi_name
  src/pyhf/pdf.py
  src/pyhf/workspace.py
  tests/test_import.py
  tests/test_pdf.py
  tests/test_schema.py
  tests/test_validation.py
  tests/test_workspace.py
Labels: refactor

#841 docs: Add FAQs on validation
  docs/faq.rst
Labels: docs

#842 fix: Get full history for Tag Creator workflow
  .github/workflows/tag.yml
Labels: CI, fix

#843 ci: Use actions-gh-pages GitHub Action for deploy of docs
  .github/workflows/ci.yml
Labels: CI

#844 docs: List the dev team as authors
  AUTHORS
  README.rst
Labels: docs
