Repository scikit-hep/pyhf, pull requests merged in 2020-02, with the labels that each got.

#765 chore: Remove accidentally added Untitled notebook
  docs/conf.py
  docs/examples/notebooks/binderexample/Untitled.ipynb
Labels: chore

#752 feat: Combine is taught about formal data (outer) join methods
  src/pyhf/cli/spec.py
  src/pyhf/workspace.py
  tests/test_workspace.py
Labels: API, feat/enhancement, fix

#759 docs: Add Stack Overflow question section
  README.md
  docs/faq.rst
Labels: docs

#770 fix: Minor typo in GitHub Actions removeLabels to removeLabel
  .github/workflows/tag.yml
Labels: CI, fix

#771 fix: Add key to workflow dictionary to make it valid JavaScript
  .github/workflows/tag.yml
Labels: CI, fix

#774 feat: Update required_parset to pass in sample data and modifier data
  src/pyhf/cli/spec.py
  src/pyhf/modifiers/__init__.py
  src/pyhf/modifiers/histosys.py
  src/pyhf/modifiers/lumi.py
  src/pyhf/modifiers/normfactor.py
  src/pyhf/modifiers/normsys.py
  src/pyhf/modifiers/shapefactor.py
  src/pyhf/modifiers/shapesys.py
  src/pyhf/modifiers/staterror.py
  src/pyhf/pdf.py
  tests/test_modifiers.py
Labels: API, refactor

#775 feat: Only allocate shapesys parameter if yield and uncrt are positive, nonzero
  docs/likelihood.rst
  src/pyhf/modifiers/shapesys.py
  src/pyhf/pdf.py
  tests/test_combined_modifiers.py
  tests/test_pdf.py
  tests/test_validation.py
Labels: docs, feat/enhancement

#777 docs: Add Les Houches 2019 New Physics Working Group Report citation
  docs/bib/use_citations.bib
Labels: docs
