Repository scikit-hep/pyhf, pull requests merged in 2021-03, with the labels that each got.

#1343 docs: Add record for published ATLAS likelihoods from November 2020
  docs/bib/HEPData_likelihoods.bib
Labels: docs

#1344 docs: Clarify and harmonize docstrings for fit parameters
  src/pyhf/infer/__init__.py
  src/pyhf/infer/calculators.py
  src/pyhf/infer/mle.py
  src/pyhf/infer/test_statistics.py
  src/pyhf/optimize/common.py
  src/pyhf/optimize/mixins.py
Labels: docs

#1345 docs: Add and apply blacken-docs as a pre-commit hook
  .pre-commit-config.yaml
  README.rst
  docs/babel.rst
  docs/development.rst
  docs/likelihood.rst
Labels: docs

#1351 fix: Retain continuous approximation of Poisson in torch v1.8.0
  src/pyhf/tensor/pytorch_backend.py
  tests/test_tensor.py
Labels: fix, tests

#1347 docs: Add use citation for Artificial Proto-Modelling paper
  docs/bib/use_citations.bib
Labels: docs

#1353 ci: Run docs CI on push events only from PR merges
  .github/workflows/docs.yml
Labels: CI

#1354 refactor: Use torch APIs for ravel, tile, and outer tensorlib methods
  setup.py
  src/pyhf/tensor/pytorch_backend.py
Labels: build, docs, refactor

#1355 test: Test lower bounds of dependencies
  .github/workflows/lower-bound-requirements.yml
  .pre-commit-config.yaml
  MANIFEST.in
  lower-bound-requirements.txt
  setup.py
Labels: CI, build, tests

#1357 docs: Add v0.6.1 release notes
  docs/release-notes.rst
  docs/release-notes/v0.6.1.rst
Labels: bumpversion/patch, docs

#1364 fix: Adjust sbottom region A regression test tolerance for GHA runner change
  tests/test_regression.py
Labels: fix

#1369 fix: Set precision for ones and zeros through dtype arg
  src/pyhf/tensor/jax_backend.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  tests/test_optim.py
  tests/test_tensor.py
Labels: fix, tests

#1375 fix: Correct JAX tensor type in docstring
  src/pyhf/tensor/jax_backend.py
Labels: docs

#1380 ci: Upload coverage to Codecov in flagged stages for complete coverage report
  .github/workflows/ci.yml
Labels: CI

#1379 chore: Ignore JAX tensor type in doctest
  src/pyhf/tensor/jax_backend.py
Labels: chore

#1384 ci: Simplify CodeQL scan setup
  .github/workflows/codeql-analysis.yml
Labels: CI, chore

#1382 build: Set only lower bounds on core dependencies
  .github/workflows/lower-bound-requirements.yml
  lower-bound-requirements.txt
  setup.cfg
Labels: build

#1383 feat: Use PyYAML's safe_load for better security
  src/pyhf/utils.py
Labels: feat/enhancement

#1306 fix: Loosen iminuit tolerances for optimization tests
  lower-bound-requirements.txt
  setup.py
  tests/test_optim.py
Labels: fix, tests
