Repository scikit-hep/pyhf, pull requests merged in 2022-06, with the labels that each got.

#1876 docs: Update Matthew's affiliation to University of Wisconsin-Madison
  .zenodo.json
  CITATION.cff
Labels: docs

#1877 ci: Add 'name-tests-test' to pre-commit hooks
  .pre-commit-config.yaml
Labels: CI

#1879 ci: Use `github.workflow` property to ensure unique concurrency group
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/notebooks.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
  .github/workflows/semantic-pr-check.yml
Labels: CI, chore

#1881 build: Use `find_namespace:` to ensure discovery of package data
  setup.cfg
Labels: build, packaging

#1883 build: Use `license_files` in setup.cfg
  setup.cfg
Labels: build, packaging

#1845 feat: Allow for clipping negative yields in the main model
  src/pyhf/pdf.py
  tests/test_pdf.py
Labels: feat/enhancement, research, tests, optimization, API, user request

#1892 ci: Use '--pytest-test-first' option for naming clarity
  .pre-commit-config.yaml
Labels: CI, chore

#1895 build: Update lower bound on iminuit to v2.7.0
  setup.py
  tests/constraints.txt
Labels: fix, build, dependencies

#1896 docs: Add use citation from Audrey Kvam's Ph.D. thesis
  docs/bib/use_citations.bib
Labels: docs

#1897 docs: Update use citations published in journals in June 2022
  docs/bib/use_citations.bib
Labels: docs, chore

#1898 chore: Use actions/setup-python v4
  .github/workflows/bump-version.yml
  .github/workflows/ci.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/lower-bound-requirements.yml
  .github/workflows/notebooks.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
Labels: CI, chore

#1900 ci: Enable Dependabot version updates for GitHub Actions
  .github/dependabot.yml
Labels: CI

#1906 chore: Update Docker GitHub Actions to Dependabot bumped versions
  .github/workflows/docker.yml
Labels: CI, chore, dependencies
