Repository scikit-hep/pyhf, pull requests merged in 2022-08, with the labels that each got.

#1926 docs: Update lower bound on Sphinx to v5.1.1
  setup.py
Labels: docs, build

#1919 fix: Manually set uncertainties for fixed parameters to 0
  src/pyhf/optimize/mixins.py
  src/pyhf/optimize/opt_minuit.py
  tests/test_optim.py
Labels: tests, fix, build

#1929 docs: Add July 2022 use citations
  docs/bib/use_citations.bib
Labels: docs

#1930 docs: Add use citation from Lucas Santiago Borgna's Ph.D. thesis
  docs/bib/use_citations.bib
Labels: docs

#1931 fix: Coverage for importing XML channels with no data
  src/pyhf/readxml.py
  tests/test_import.py
  tests/test_import/xmlimport_noChannelData/config/HistFactorySchema.dtd
  tests/test_import/xmlimport_noChannelData/config/example.xml
  tests/test_import/xmlimport_noChannelData/config/example_channel.xml
Labels: tests, fix

#1933 fix: Handle importing XML measurements with no POI attribute
  src/pyhf/readxml.py
  tests/test_import.py
  tests/test_import/xmlimport_missingPOI/config/HistFactorySchema.dtd
  tests/test_import/xmlimport_missingPOI/config/example.xml
  tests/test_import/xmlimport_missingPOI/config/example_channel.xml
Labels: tests, fix

#1909 feat: Handle absolute paths in XML config files (xml2json / readxml)
  src/pyhf/cli/rootio.py
  src/pyhf/readxml.py
  src/pyhf/utils.py
  tests/test_import.py
  tests/test_scripts.py
  tests/test_scripts/xmlimport_absolutePaths/config/HistFactorySchema.dtd
  tests/test_scripts/xmlimport_absolutePaths/config/example.xml
  tests/test_scripts/xmlimport_absolutePaths/config/example_channel.xml
  tests/test_scripts/xmlimport_absolutePaths/data/example.root
Labels: feat/enhancement, tests, CLI

#1936 ci: Report coverage for all Python versions
  .github/workflows/ci.yml
Labels: CI, chore

#1934 feat: Enable typehints in pre-commit and add typehints to readxml
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  src/pyhf/readxml.py
  src/pyhf/schema/validator.py
  src/pyhf/typing.py
  tests/test_import.py
Labels: feat/enhancement, CI, pre-commit

#1937 test: Ignore TYPE_CHECKING for coverage
  .coveragerc
Labels: CI, fix

#1938 build: Set lower bound of typing-extensions to v3.7.4
  setup.cfg
  tests/constraints.txt
Labels: build

#1887 ci: Make `build` error on warnings
  .github/workflows/publish-package.yml
Labels: CI, packaging

#1943 chore: Remove 'lint' extra from setup.py
  .github/workflows/lint.yml
  setup.py
Labels: CI, chore

#1942 refactor: Use string literal types of generic builtins for type checking
  .coveragerc
  src/pyhf/typing.py
Labels: refactor, revert, type checking

#1951 build: Update git archival options to support auto versioning
  .git_archival.txt
  pyproject.toml
Labels: build, chore

#1954 ci: Use 'strict' option for twine check
  .github/workflows/publish-package.yml
Labels: CI, chore

#1953 feat: Validate workspace specification before accessing parts of it
  src/pyhf/workspace.py
  tests/test_workspace.py
Labels: feat/enhancement, tests

#1955 ci: Deploy GitHub Pages docs directly using GitHub Actions
  .github/workflows/docs.yml
Labels: docs, CI

#1917 fix: Populate the schema cache with local `defs.json` again
  setup.py
  src/pyhf/schema/__init__.py
  src/pyhf/schema/loader.py
  tests/test_schema.py
Labels: tests, fix

#1940 feat: Add typehints to pyhf.tensor
  .coveragerc
  .pre-commit-config.yaml
  codecov.yml
  pyproject.toml
  src/pyhf/readxml.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/typing.py
Labels: feat/enhancement, docs, type checking

#1958 build: Update lower bound of click to v8.0.0
  setup.cfg
  tests/constraints.txt
Labels: fix, build, dependencies

#1961 build: Update lower bound of typing-extensions to v3.7.4.3
  setup.cfg
  tests/constraints.txt
Labels: fix, build

#1962 build: Update lower bounds to tensorflow v2.7.0, jaxlib v0.1.61
  setup.py
  tests/constraints.txt
Labels: fix, build

#1960 ci: Restrict deployments of environments to PR merges
  .github/workflows/docs.yml
Labels: CI, fix

#1956 docs: Add link to public-probability-models website
  docs/citations.rst
Labels: docs

#1965 fix: Keep staterror from affecting multiple samples
  src/pyhf/modifiers/staterror.py
  tests/test_modifiers.py
  tests/test_modifiers/issue1720_greedy_staterror.json
  tests/test_scripts.py
Labels: tests, fix

#1968 ci: Publish to PyPI on publish of GitHub release
  .github/workflows/publish-package.yml
Labels: CI, fix

#1969 docs: Add typehint aliases
  docs/conf.py
  src/pyhf/tensor/numpy_backend.py
Labels: docs

#1976 fix: Base URI for jsonschema.RefResolver has better behavior
  src/pyhf/schema/validator.py
Labels: schema and spec, fix, validation
