Repository scikit-hep/pyhf, pull requests merged in 2023-11, with the labels that each got.

#2373 build: Remove installation of backends from 'test' extra
  .github/workflows/ci-windows.yml
  .github/workflows/ci.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/lower-bound-requirements.yml
  .github/workflows/notebooks.yml
  noxfile.py
  pyproject.toml
Labels: CI, build

#2376 fix: Access jax.config from jax
  src/pyhf/tensor/jax_backend.py
Labels: fix, need-to-backport

#2380 fix: Add filterwarnings ignore for virtualized device UserWarning
  pyproject.toml
Labels: fix, chore, need-to-backport

#2381 chore: Use Ruff lint config
  pyproject.toml
Labels: chore, need-to-backport

#2382 chore: Add pre-commit/pygrep-hooks to pre-commit hooks
  .pre-commit-config.yaml
  docs/index.rst
Labels: chore, pre-commit, need-to-backport

#2383 chore: Use native Ruff Jupyter support
  .pre-commit-config.yaml
  pyproject.toml
Labels: chore, pre-commit, need-to-backport

#2384 test: Use tmp_path pytest fixture over tmpdir
  tests/conftest.py
  tests/contrib/test_contrib_utils.py
  tests/test_examples.py
  tests/test_infer.py
  tests/test_notebooks.py
  tests/test_scripts.py
Labels: tests, chore
