Repository scikit-hep/pyhf, pull requests merged in 2024-05, with the labels that each got.

#2475 ci: Use uv for install on ReadTheDocs
  .readthedocs.yaml
Labels: docs, CI, need-to-backport

#2477 docs: Use importlib.metadata to get version info
  docs/conf.py
Labels: docs, need-to-backport

#2473 ci: Add GitHub artifact attestations to package distribution
  .github/workflows/publish-package.yml
Labels: CI, need-to-backport

#2479 ci: Place upper bound on min supported setuptools
  .github/workflows/lower-bound-requirements.yml
Labels: CI, fix, need-to-backport

#2480 ci: Add python-jsonschema/check-jsonschema pre-commit hook
  .github/workflows/bump-version.yml
  .github/workflows/publish-package.yml
  .pre-commit-config.yaml
Labels: CI, need-to-backport

#2481 ci: Update permissions for GitHub attestations
  .github/workflows/publish-package.yml
Labels: CI, chore, need-to-backport

#2482 ci: Add OSSF Scorecard GitHub action
  .github/workflows/scorecard.yml
Labels: CI, need-to-backport

#2484 ci: Restrict content permissions to harden GitHub Actions
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
Labels: CI, security

#2485 chore: Use uv during Dockerfile build
  docker/Dockerfile
Labels: chore, Docker, need-to-backport

#2486 chore: Speed up pyhf CLI API execution for Docker users
  docker/Dockerfile
Labels: chore, Docker, need-to-backport

#2489 ci: Don't test warnings on release tests
  .github/workflows/release_tests.yml
Labels: CI, need-to-backport

#2491 build(backport): Determine tensorflow-probability requirements from python version
  pyproject.toml
Labels: backport

#2492 chore(backport): Update pre-commit hooks
  .github/workflows/bump-version.yml
  .github/workflows/publish-package.yml
  .pre-commit-config.yaml
  docs/examples/notebooks/ImpactPlot.ipynb
  src/pyhf/cli/__init__.py
  src/pyhf/cli/cli.py
  src/pyhf/cli/complete.py
  src/pyhf/cli/infer.py
  src/pyhf/cli/patchset.py
  src/pyhf/cli/rootio.py
  src/pyhf/cli/spec.py
  src/pyhf/contrib/cli.py
  src/pyhf/contrib/viz/brazil.py
  src/pyhf/infer/calculators.py
  src/pyhf/infer/intervals/__init__.py
  src/pyhf/infer/intervals/upper_limits.py
  src/pyhf/infer/mle.py
  src/pyhf/interpolators/code0.py
  src/pyhf/interpolators/code1.py
  src/pyhf/interpolators/code2.py
  src/pyhf/interpolators/code4.py
  src/pyhf/interpolators/code4p.py
  src/pyhf/modifiers/shapesys.py
  src/pyhf/modifiers/staterror.py
  src/pyhf/optimize/common.py
  src/pyhf/optimize/mixins.py
  src/pyhf/optimize/opt_minuit.py
  src/pyhf/optimize/opt_scipy.py
  src/pyhf/optimize/opt_tflow.py
  src/pyhf/parameters/paramview.py
  src/pyhf/patchset.py
  src/pyhf/probability.py
  src/pyhf/schema/__init__.py
  src/pyhf/tensor/numpy_backend.py
  src/pyhf/tensor/pytorch_backend.py
  src/pyhf/tensor/tensorflow_backend.py
  src/pyhf/typing.py
  src/pyhf/workspace.py
  tests/test_interpolate.py
Labels: backport

#2493 ci(backport): Update GitHub Actions
  .github/workflows/bump-version.yml
  .github/workflows/ci.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/docs.yml
  .github/workflows/notebooks.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
  pyproject.toml
Labels: CI, backport

#2494 ci(backport): Use uv for all pip installs
  .github/workflows/bump-version.yml
  .github/workflows/ci.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/docs.yml
  .github/workflows/notebooks.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
  .readthedocs.yaml
Labels: backport

#2495 test(backport): Use coverage over pytest-cov
  .coveragerc
  .github/workflows/ci.yml
  pyproject.toml
Labels: backport

#2496 ci(backport): Add GitHub artifact attestations to package distribution
  .github/workflows/publish-package.yml
Labels: CI, backport

#2497 test(backport): Lower tolerance for agreement between amd64 and arm64
  tests/test_calculator.py
Labels: tests, backport

#2498 docs(backport): Add automatic release notes config file
  .github/release.yml
Labels: docs, community, backport

#2499 fix(backport): Test xml.etree.ElementTree.Element truth value by 'is not None'
  src/pyhf/writexml.py
  tests/test_export.py
Labels: tests, fix, backport

#2500 feat(backport): Use Python 3.12+ tarfile data extraction filter
  src/pyhf/contrib/utils.py
Labels: feat/enhancement, fix, contrib, backport

#2502 docs(backport): Use importlib.metadata to get version info
  docs/conf.py
Labels: docs, backport

#2503 chore(backport): Use uv during Dockerfile build
  docker/Dockerfile
Labels: chore, Docker, backport

#2504 chore(backport): Update services and docs to Python 3.12 as default
  binder/runtime.txt
  codemeta.json
  docs/development.rst
  pyproject.toml
Labels: backport

#2505 ci(backport): Update CI permissions changes
  .github/workflows/bump-version.yml
  .github/workflows/ci-windows.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/lower-bound-requirements.yml
  .github/workflows/merged.yml
  .github/workflows/notebooks.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
  .github/workflows/semantic-pr-check.yml
Labels: backport

#2490 chore: Remove codemeta from repository
  .github/ISSUE_TEMPLATE/~release-checklist.md
  .github/workflows/release_tests.yml
  codemeta.json
  docs/development.rst
  pyproject.toml
  tbump.toml
Labels: docs, chore, need-to-backport

#2506 chore(backport): Remove codemeta from repository
  .github/ISSUE_TEMPLATE/~release-checklist.md
  .github/workflows/release_tests.yml
  codemeta.json
  docs/development.rst
  pyproject.toml
  tbump.toml
Labels: chore, backport

#2507 build: Use notebook over jupyter
  pyproject.toml
Labels: build, chore, need-to-backport

#2508 build(backport): Use notebook over jupyter
  pyproject.toml
Labels: build, chore, backport
