Repository scikit-hep/pyhf, pull requests merged in 2024-04, with the labels that each got.

#2468 ci: Use 'macos-13' runs-on to continue using x86 based macOS runners
  .github/workflows/ci.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/release_tests.yml
Labels: CI, need-to-backport

#2469 build: Update scipy lower bound to v1.5.2
  pyproject.toml
  tests/constraints.txt
Labels: tests, fix, build, dependencies, need-to-backport

#2471 ci: Use Apple silicon for the default macOS runners
  .github/workflows/ci.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/release_tests.yml
Labels: CI, need-to-backport

#2472 build: Use lower bounds for all dependencies
  pyproject.toml
Labels: build, chore, need-to-backport

#2444 ci: Use uv for all pip installs
  .github/workflows/bump-version.yml
  .github/workflows/ci-windows.yml
  .github/workflows/ci.yml
  .github/workflows/dependencies-head.yml
  .github/workflows/docs.yml
  .github/workflows/lower-bound-requirements.yml
  .github/workflows/notebooks.yml
  .github/workflows/publish-package.yml
  .github/workflows/release_tests.yml
  .readthedocs.yaml
  pyproject.toml
Labels: CI, need-to-backport
