Repository scikit-hep/pyhf, pull requests merged in 2024-07, with the labels that each got.

#2528 chore(backport): Update pre-commit hooks
  .pre-commit-config.yaml
Labels: chore, backport

#2531 build(backport): bump actions/upload-artifact to 4.3.4
  .github/workflows/publish-package.yml
Labels: backport

#2533 build(backport): bump actions/attest-build-provenance from 1.3.2 to 1.3.3 in the actions group
  .github/workflows/publish-package.yml
Labels: dependencies, github-actions
